"""Professional Invoice PDF generator — ReportLab.

Layout matches reference Fattura 7/2026:
- Logo top-left, company name/details top-right
- Thin blue divider line
- FATTURA N. XX/XXXX centered and large
- DATA FATTURA | TIPO in two side-by-side boxes below title
- Items table: navy header, white rows, no alternating colors
- Totals block: right-aligned, subtotals plain, total with navy bg
- Coordinate bancarie: left blue bar box
- Scadenza pagamenti: left blue bar box below
- Footer: generated by line + page number
"""
from io import BytesIO
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_RIGHT, TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable
)
from reportlab.platypus.flowables import PageBreak

COL_NAVY        = colors.HexColor("#1E3A5F")
COL_ACCENT      = colors.HexColor("#0055FF")
COL_DARK        = colors.HexColor("#1a1a2e")
COL_GRAY        = colors.HexColor("#64748b")
COL_LIGHT_GRAY  = colors.HexColor("#F1F5F9")
COL_BORDER      = colors.HexColor("#CBD5E1")
COL_ROW_BORDER  = colors.HexColor("#E2E8F0")
COL_WHITE       = colors.white

DOC_TYPE_NAMES = {
    "FT": "FATTURA",
    "PRV": "PREVENTIVO",
    "DDT": "DOCUMENTO DI TRASPORTO",
    "NC": "NOTA DI CREDITO",
}

PAYMENT_METHOD_NAMES = {
    "bonifico": "Bonifico Bancario a Vista",
    "contanti": "Contanti",
    "carta": "Carta di Credito",
    "assegno": "Assegno",
    "riba": "RiBa",
    "altro": "Altro",
}

PAGE_W = A4[0] - 32*mm


def _fmt(n) -> str:
    try:
        val = float(n or 0)
    except (ValueError, TypeError):
        return "0,00"
    s = f"{val:,.2f}"
    return s.replace(",", "X").replace(".", ",").replace("X", ".")


def _s(val) -> str:
    return str(val or "")


def _date(d) -> str:
    if isinstance(d, datetime):
        return d.strftime("%d/%m/%Y")
    if isinstance(d, str):
        try:
            return datetime.fromisoformat(d.replace("Z", "+00:00")).strftime("%d/%m/%Y")
        except Exception:
            return d
    return ""


def _left_bar_box(content_rows, col_width):
    """Box with left blue accent bar, white background, light border."""
    accent = Table([['']], colWidths=[3*mm], style=TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), COL_ACCENT),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
    ]))
    inner = Table(content_rows, colWidths=[col_width - 5*mm], style=TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), COL_WHITE),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ]))
    outer = Table([[accent, inner]], colWidths=[3*mm, col_width - 3*mm])
    outer.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('BOX', (0,0), (-1,-1), 0.5, COL_BORDER),
    ]))
    return outer


def _styles():
    S = {}
    S['company_name'] = ParagraphStyle(
        'company_name', fontSize=12, fontName='Helvetica-Bold',
        textColor=COL_ACCENT, alignment=TA_RIGHT, spaceAfter=2
    )
    S['company_detail'] = ParagraphStyle(
        'company_detail', fontSize=7.5, fontName='Helvetica',
        textColor=COL_GRAY, alignment=TA_RIGHT, leading=12
    )
    S['doc_title'] = ParagraphStyle(
        'doc_title', fontSize=18, fontName='Helvetica-Bold',
        textColor=COL_NAVY, alignment=TA_CENTER, spaceAfter=0
    )
    S['box_label'] = ParagraphStyle(
        'box_label', fontSize=7, fontName='Helvetica-Bold',
        textColor=COL_GRAY, spaceAfter=2, leading=10
    )
    S['box_value'] = ParagraphStyle(
        'box_value', fontSize=9, fontName='Helvetica',
        textColor=COL_DARK, leading=13
    )
    S['spett'] = ParagraphStyle(
        'spett', fontSize=7, fontName='Helvetica-Bold',
        textColor=COL_GRAY, spaceAfter=2
    )
    S['client_name'] = ParagraphStyle(
        'client_name', fontSize=11, fontName='Helvetica-Bold',
        textColor=COL_NAVY, spaceAfter=2
    )
    S['client_detail'] = ParagraphStyle(
        'client_detail', fontSize=8, fontName='Helvetica',
        textColor=colors.HexColor("#475569"), leading=13
    )
    S['th'] = ParagraphStyle(
        'th', fontSize=8, fontName='Helvetica-Bold',
        textColor=COL_WHITE, alignment=TA_LEFT
    )
    S['th_r'] = ParagraphStyle(
        'th_r', fontSize=8, fontName='Helvetica-Bold',
        textColor=COL_WHITE, alignment=TA_RIGHT
    )
    S['th_c'] = ParagraphStyle(
        'th_c', fontSize=8, fontName='Helvetica-Bold',
        textColor=COL_WHITE, alignment=TA_CENTER
    )
    S['td'] = ParagraphStyle(
        'td', fontSize=8.5, fontName='Helvetica',
        textColor=COL_DARK, leading=12
    )
    S['td_r'] = ParagraphStyle(
        'td_r', fontSize=8.5, fontName='Helvetica',
        textColor=COL_DARK, alignment=TA_RIGHT, leading=12
    )
    S['td_c'] = ParagraphStyle(
        'td_c', fontSize=8.5, fontName='Helvetica',
        textColor=COL_DARK, alignment=TA_CENTER, leading=12
    )
    S['total_label'] = ParagraphStyle(
        'total_label', fontSize=8.5, fontName='Helvetica',
        textColor=COL_GRAY, alignment=TA_LEFT
    )
    S['total_value'] = ParagraphStyle(
        'total_value', fontSize=8.5, fontName='Helvetica',
        textColor=COL_DARK, alignment=TA_RIGHT
    )
    S['grand_label'] = ParagraphStyle(
        'grand_label', fontSize=10, fontName='Helvetica-Bold',
        textColor=COL_WHITE, alignment=TA_LEFT
    )
    S['grand_value'] = ParagraphStyle(
        'grand_value', fontSize=13, fontName='Helvetica-Bold',
        textColor=COL_WHITE, alignment=TA_RIGHT
    )
    S['section_title'] = ParagraphStyle(
        'section_title', fontSize=8, fontName='Helvetica-Bold',
        textColor=COL_ACCENT, spaceAfter=3
    )
    S['section_detail'] = ParagraphStyle(
        'section_detail', fontSize=8.5, fontName='Helvetica',
        textColor=COL_DARK, leading=14
    )
    S['legal'] = ParagraphStyle(
        'legal', fontSize=6.5, fontName='Helvetica',
        textColor=COL_GRAY, leading=10, alignment=TA_LEFT
    )
    S['footer_center'] = ParagraphStyle(
        'footer_center', fontSize=6.5, fontName='Helvetica',
        textColor=COL_GRAY, alignment=TA_CENTER, leading=10
    )
    S['reg_footer'] = ParagraphStyle(
        'reg_footer', fontSize=7.5, fontName='Helvetica-Bold',
        textColor=COL_ACCENT, alignment=TA_CENTER
    )
    return S


def generate_modern_invoice_pdf(invoice: dict, client: dict, company: dict) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=16*mm, rightMargin=16*mm,
        topMargin=14*mm, bottomMargin=16*mm,
    )

    S = _styles()
    co = company or {}
    cl = client or {}
    story = []

    # ── 1. HEADER: logo left, company right ──
    company_name = _s(co.get("business_name"))
    addr = _s(co.get("address"))
    cap = _s(co.get("cap"))
    city = _s(co.get("city"))
    prov = _s(co.get("province"))
    piva = _s(co.get("partita_iva"))
    cf = _s(co.get("codice_fiscale"))
    phone = _s(co.get("phone") or co.get("tel"))
    email = _s(co.get("email") or co.get("contact_email"))

    addr_parts = []
    if addr: addr_parts.append(addr)
    loc = " ".join(p for p in [cap, city, f"({prov})" if prov else ""] if p)
    if loc: addr_parts.append(loc)
    if piva: addr_parts.append(f"P.IVA: {piva}")
    if cf and cf != piva: addr_parts.append(f"C.F.: {cf}")
    if phone: addr_parts.append(f"Tel: {phone}")
    if email: addr_parts.append(f"Email: {email}")

    logo_cell = Spacer(1, 1)
    logo_url = co.get("logo_url", "")
    if logo_url and logo_url.startswith("data:image"):
        try:
            import base64
            from reportlab.platypus import Image as RLImage
            from io import BytesIO as BIO
            parts = logo_url.split(",", 1)
            if len(parts) == 2:
                img_data = base64.b64decode(parts[1])
                logo_cell = RLImage(BIO(img_data), width=45*mm, height=18*mm, kind='proportional')
        except Exception:
            pass

    company_right = Table([
        [Paragraph(company_name, S['company_name'])],
        [Paragraph("<br/>".join(addr_parts), S['company_detail'])],
    ], colWidths=[90*mm], style=TableStyle([
        ('ALIGN', (0,0), (-1,-1), 'RIGHT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 1),
    ]))

    header_table = Table([[logo_cell, company_right]], colWidths=[80*mm, 90*mm])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 3*mm))

    # Thin blue divider
    story.append(HRFlowable(width="100%", thickness=1.5, color=COL_ACCENT, spaceAfter=5*mm))

    # ── 2. DOC TITLE centered ──
    doc_type = invoice.get("document_type", "FT")
    doc_title_text = DOC_TYPE_NAMES.get(doc_type, "DOCUMENTO")
    doc_number = _s(invoice.get("document_number", ""))
    display_num = doc_number.replace("FT-", "").replace("NC-", "").replace("PRV-", "").replace("DDT-", "")
    issue_date = _date(invoice.get("issue_date", ""))
    due_date = invoice.get("due_date")
    payment_label = invoice.get("payment_terms") or PAYMENT_METHOD_NAMES.get(
        invoice.get("payment_method", ""), invoice.get("payment_method", "")
    )

    story.append(Paragraph(f"{doc_title_text} N. {display_num}", S['doc_title']))
    story.append(Spacer(1, 4*mm))

    # ── 3. DATA | TIPO boxes side by side ──
    tipo_label = "COMPLETA"
    if doc_type == "PRV": tipo_label = "PREVENTIVO"
    elif doc_type == "DDT": tipo_label = "TRASPORTO"
    elif doc_type == "NC": tipo_label = "NOTA CREDITO"

    date_box = Table([
        [Paragraph("DATA FATTURA" if doc_type == "FT" else f"DATA {doc_title_text}", S['box_label'])],
        [Paragraph(issue_date, S['box_value'])],
    ], colWidths=[PAGE_W * 0.48], style=TableStyle([
        ('BOX', (0,0), (-1,-1), 0.5, COL_BORDER),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('BACKGROUND', (0,0), (-1,-1), COL_WHITE),
    ]))

    tipo_box = Table([
        [Paragraph("TIPO", S['box_label'])],
        [Paragraph(tipo_label, S['box_value'])],
    ], colWidths=[PAGE_W * 0.48], style=TableStyle([
        ('BOX', (0,0), (-1,-1), 0.5, COL_BORDER),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('BACKGROUND', (0,0), (-1,-1), COL_WHITE),
    ]))

    meta_row = Table([[date_box, Spacer(PAGE_W*0.04, 1), tipo_box]],
                     colWidths=[PAGE_W*0.48, PAGE_W*0.04, PAGE_W*0.48])
    meta_row.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(meta_row)
    story.append(Spacer(1, 5*mm))

    # ── 4. CLIENT: Spett.le + name + details, right side ──
    cl_name = _s(cl.get("business_name"))
    cl_parts = []
    cl_addr = _s(cl.get("address"))
    cl_cap = _s(cl.get("cap"))
    cl_city = _s(cl.get("city"))
    cl_prov = _s(cl.get("province"))
    if cl_addr: cl_parts.append(cl_addr)
    loc2 = " ".join(p for p in [cl_cap, cl_city, f"({cl_prov})" if cl_prov else ""] if p)
    if loc2: cl_parts.append(loc2)
    cl_piva = _s(cl.get("partita_iva"))
    cl_cf = _s(cl.get("codice_fiscale"))
    cl_sdi = _s(cl.get("codice_sdi"))
    cl_pec = _s(cl.get("pec"))
    if cl_piva: cl_parts.append(f"P.IVA {cl_piva}")
    if cl_cf: cl_parts.append(f"C.F. {cl_cf}")
    if cl_sdi: cl_parts.append(f"Cod. SDI {cl_sdi}")
    if cl_pec: cl_parts.append(f"PEC {cl_pec}")

    # Left: Spett.le label + client name/address (matching reference layout)
    client_left = Table([
        [Paragraph("Spett.le", S['spett'])],
        [Paragraph(cl_name, S['client_name'])],
        [Paragraph("<br/>".join(cl_parts), S['client_detail'])],
    ], colWidths=[PAGE_W * 0.5], style=TableStyle([
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 4),
        ('TOPPADDING', (0,0), (-1,-1), 2),
        ('BOTTOMPADDING', (0,0), (-1,-1), 2),
    ]))

    story.append(client_left)
    story.append(Spacer(1, 5*mm))

    # ── 5. ITEMS TABLE ──
    lines = invoice.get("lines", [])

    table_data = [[
        Paragraph("Descrizione", S['th']),
        Paragraph("Q.tà", S['th_c']),
        Paragraph("Prezzo Unit.", S['th_r']),
        Paragraph("IVA", S['th_c']),
        Paragraph("Totale", S['th_r']),
    ]]

    for ln in lines:
        desc = _s(ln.get("description") or "").replace("\n", "<br/>")
        qty = _fmt(ln.get("quantity", 0))
        price = _fmt(ln.get("unit_price", 0))
        disc = float(ln.get("discount_percent") or ln.get("sconto_1") or 0)
        disc2 = float(ln.get("sconto_2") or 0)
        # Include discount in description if present
        if disc > 0:
            disc_str = f"Sconto: {_fmt(disc)}%"
            if disc2 > 0:
                disc_str += f" + {_fmt(disc2)}%"
            desc += f"<br/><font size='7' color='#64748b'>{disc_str}</font>"
        vat = _s(str(ln.get("vat_rate", "22")))
        total = _fmt(ln.get("line_total", 0))

        table_data.append([
            Paragraph(desc, S['td']),
            Paragraph(qty, S['td_c']),
            Paragraph(f"€ {price}", S['td_r']),
            Paragraph(f"{vat}%", S['td_c']),
            Paragraph(f"€ {total}", S['td_r']),
        ])

    cw = [PAGE_W*0.46, PAGE_W*0.08, PAGE_W*0.16, PAGE_W*0.10, PAGE_W*0.20]
    items_table = Table(table_data, colWidths=cw, repeatRows=1)
    items_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), COL_NAVY),
        ('TEXTCOLOR', (0,0), (-1,0), COL_WHITE),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 8),
        ('TOPPADDING', (0,0), (-1,0), 9),
        ('BOTTOMPADDING', (0,0), (-1,0), 9),
        ('LEFTPADDING', (0,0), (-1,-1), 7),
        ('RIGHTPADDING', (0,0), (-1,-1), 7),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,1), (-1,-1), 8.5),
        ('TOPPADDING', (0,1), (-1,-1), 8),
        ('BOTTOMPADDING', (0,1), (-1,-1), 8),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BACKGROUND', (0,1), (-1,-1), COL_WHITE),
        ('LINEBELOW', (0,0), (-1,-1), 0.5, COL_ROW_BORDER),
        ('LINEBELOW', (0,-1), (-1,-1), 1.5, COL_NAVY),
    ]))
    story.append(items_table)
    story.append(Spacer(1, 5*mm))

    # ── 6. TOTALS right-aligned ──
    from services.pdf_template import compute_iva_groups
    iva_data = compute_iva_groups(lines)
    totals_inv = invoice.get("totals", {})
    ritenuta = float(totals_inv.get("ritenuta", 0) or 0)

    subtotal_rows = [
        [Paragraph("Imponibile:", S['total_label']), Paragraph(f"€ {_fmt(iva_data['imponibile'])}", S['total_value'])],
    ]
    subtotal_rows.append([
        Paragraph("IVA:", S['total_label']),
        Paragraph(f"€ {_fmt(iva_data['total_vat'])}", S['total_value']),
    ])
    if ritenuta > 0:
        subtotal_rows.append([
            Paragraph("Ritenuta d'acconto:", S['total_label']),
            Paragraph(f"-€ {_fmt(ritenuta)}", S['total_value']),
        ])

    sub_table = Table(subtotal_rows, colWidths=[45*mm, 35*mm])
    sub_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('LEFTPADDING', (0,0), (-1,-1), 5),
        ('RIGHTPADDING', (0,0), (-1,-1), 5),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('BACKGROUND', (0,0), (-1,-1), COL_WHITE),
        ('LINEBELOW', (0,0), (-1,-2), 0.3, COL_ROW_BORDER),
    ]))

    netto = iva_data["total"] - ritenuta if ritenuta > 0 else iva_data["total"]
    grand_table = Table([
        [Paragraph("TOTALE:", S['grand_label']),
         Paragraph(f"€ {_fmt(netto)}", S['grand_value'])],
    ], colWidths=[45*mm, 35*mm])
    grand_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), COL_NAVY),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('LEFTPADDING', (0,0), (-1,-1), 5),
        ('RIGHTPADDING', (0,0), (-1,-1), 5),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
    ]))

    totals_block = Table([[sub_table], [grand_table]], colWidths=[80*mm])
    totals_block.setStyle(TableStyle([
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
    ]))

    # Right-align totals block
    totals_row = Table([[Spacer(PAGE_W - 80*mm, 1), totals_block]],
                       colWidths=[PAGE_W - 80*mm, 80*mm])
    totals_row.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(totals_row)
    story.append(Spacer(1, 6*mm))

    # ── 7. COORDINATE BANCARIE (left blue bar box) ──
    bank = co.get("bank_details", {}) or {}
    bank_name = _s(bank.get("bank_name", ""))
    bank_iban = _s(bank.get("iban", ""))
    bank_bic = _s(bank.get("bic_swift", ""))

    bank_parts = []
    if bank_name and bank_iban:
        bank_parts.append(f"<b>{bank_name}</b> - IBAN {bank_iban}")
    elif bank_iban:
        bank_parts.append(f"IBAN {bank_iban}")
    if bank_bic:
        bank_parts.append(f"BIC/SWIFT: {bank_bic}")

    if bank_parts:
        bank_box = _left_bar_box([
            [Paragraph("Coordinate Bancarie:", S['section_title'])],
            [Paragraph("<br/>".join(bank_parts), S['section_detail'])],
        ], PAGE_W)
        story.append(bank_box)
        story.append(Spacer(1, 3*mm))

    # ── 8. SCADENZA PAGAMENTI (left blue bar box) ──
    payment_type_label = _s(invoice.get("payment_type_label", "")) or _s(payment_label)
    scad_parts = []
    if payment_type_label:
        scad_parts.append(f"<b>Condizioni:</b> {payment_type_label}")
    if due_date:
        scad_parts.append(f"<b>Scadenza:</b> {_date(due_date)}")

    if scad_parts:
        scad_box = _left_bar_box([
            [Paragraph("SCADENZA PAGAMENTI", S['section_title'])],
            [Paragraph("<br/>".join(scad_parts), S['section_detail'])],
        ], PAGE_W)
        story.append(scad_box)
        story.append(Spacer(1, 5*mm))

    # ── 9. NOTES ──
    if invoice.get("notes"):
        notes_box = _left_bar_box([
            [Paragraph("NOTE", S['section_title'])],
            [Paragraph(_s(invoice["notes"]).replace("\n", "<br/>"), S['section_detail'])],
        ], PAGE_W)
        story.append(notes_box)
        story.append(Spacer(1, 5*mm))

    # ── 10. FOOTER ──
    story.append(HRFlowable(width="100%", thickness=0.5, color=COL_BORDER))
    story.append(Spacer(1, 2*mm))

    now_str = datetime.now().strftime("%d/%m/%Y %H:%M")
    footer_row = Table([[
        Paragraph(f"Generato da {company_name} - NormaFacile", S['footer_center']),
        Paragraph(f"Documento generato il {now_str}", S['footer_center']),
    ]], colWidths=[PAGE_W*0.5, PAGE_W*0.5])
    footer_row.setStyle(TableStyle([
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(footer_row)
    story.append(Spacer(1, 1.5*mm))
    story.append(Paragraph(
        "Azienda Certificata EN 1090-1 EXC3  •  ISO 3834-2  •  Centro di Trasformazione Acciaio",
        S['reg_footer']
    ))

    # ── CONDITIONS PAGE (solo Preventivi) ──
    condizioni = co.get("condizioni_vendita", "") or ""
    if condizioni.strip() and doc_type == "PRV":
        story.append(PageBreak())
        story.append(Paragraph("CONDIZIONI GENERALI DI VENDITA", ParagraphStyle(
            'ct', fontSize=11, fontName='Helvetica-Bold',
            textColor=COL_NAVY, alignment=TA_CENTER, spaceAfter=8
        )))
        story.append(Paragraph(condizioni.replace("\n", "<br/>"), ParagraphStyle(
            'ctext', fontSize=7.5, fontName='Helvetica', leading=11, alignment=4
        )))

    doc.build(story)
    buf.seek(0)
    return buf.getvalue()
