[phases.setup]
aptPkgs = ["poppler-utils", "libpango-1.0-0", "libpangoft2-1.0-0", "libharfbuzz0b", "libfontconfig1", "libgdk-pixbuf2.0-0", "libcairo2", "libpangocairo-1.0-0"]

[phases.install]
cmds = ["pip install -r requirements.txt --extra-index-url https://d33sy5i8bnduwe.cloudfront.net/simple/"]
