"""Content Engine — Seed data for 10 pre-loaded content sources."""

CONTENT_SOURCES_SEED = [
    {
        "title": "Registro Obblighi Commessa",
        "type": "feature",
        "category": "compliance",
        "description": "Un unico registro che raccoglie tutti gli obblighi di una commessa da 8 fonti diverse: contratto, normativa, sicurezza, materiali, personale, documentazione, certificazione, ambiente. Mostra cosa manca, cosa blocca e chi deve intervenire.",
        "target_audience": ["titolare", "ufficio_tecnico", "qualita"],
        "pain_points": ["documenti sparsi in 10 posti diversi", "obblighi scoperti tardi quando bloccano la consegna", "non sapere cosa manca finche non arriva l'auditor", "perdere ore a ricostruire lo stato di una commessa"],
        "value_claim": "Tutto quello che serve per chiudere una commessa, visibile in un solo posto",
        "proof_points": ["8 fonti di obblighi integrate", "semaforo blocchi hard/soft/advisory", "zero sorprese in fase di consegna"],
        "demo_route": "/commesse/com_demo_main",
    },
    {
        "title": "Istruttoria AI da Preventivo",
        "type": "feature",
        "category": "ai",
        "description": "L'intelligenza artificiale analizza un preventivo e identifica automaticamente le normative applicabili, i rischi, le classi di esecuzione e i documenti necessari. Quello che prima richiedeva ore di analisi manuale.",
        "target_audience": ["titolare", "ufficio_tecnico"],
        "pain_points": ["non sapere quale normativa si applica a ogni voce", "sbagliare la classe di esecuzione e scoprirlo dopo", "dimenticare requisiti normativi nel preventivo"],
        "value_claim": "Da preventivo a istruttoria normativa in 30 secondi, non in 3 ore",
        "proof_points": ["analisi automatica EN 1090 + EN 13241", "identificazione classe EXC", "lista obblighi pre-compilata"],
        "demo_route": "/preventivi",
    },
    {
        "title": "Segmentazione Commessa Mista",
        "type": "feature",
        "category": "compliance",
        "description": "Quando una commessa include lavorazioni diverse (strutture EN 1090, cancelli EN 13241, accessori generici), il sistema segmenta automaticamente creando rami normativi separati con requisiti specifici per ciascuno.",
        "target_audience": ["ufficio_tecnico", "qualita"],
        "pain_points": ["gestire manualmente normative diverse sulla stessa commessa", "confondere i requisiti EN 1090 con quelli EN 13241", "dimenticare una certificazione perche la commessa e mista"],
        "value_claim": "Una commessa mista, gestita come se fossero commesse specializzate separate",
        "proof_points": ["rami normativi automatici", "emissioni documentali per ramo", "evidence gate specifico per normativa"],
        "demo_route": "/commesse/com_demo_main",
    },
    {
        "title": "Evidence Gate EN 1090",
        "type": "feature",
        "category": "quality",
        "description": "Prima di emettere qualsiasi documento certificativo, il sistema verifica che tutte le evidenze richieste siano presenti. Nessun documento esce incompleto o non conforme.",
        "target_audience": ["qualita", "ufficio_tecnico"],
        "pain_points": ["emettere un fascicolo tecnico incompleto", "dimenticare un certificato 3.1 dentro un pacco", "il cliente trova errori nella documentazione consegnata"],
        "value_claim": "Zero documenti certificativi emessi senza le evidenze richieste",
        "proof_points": ["gate automatico per ogni emissione", "checklist evidenze per tipo documento", "blocco emissione se manca qualcosa"],
        "demo_route": "/commesse/com_demo_main",
    },
    {
        "title": "POS Generato da Scheda Cantiere",
        "type": "feature",
        "category": "sicurezza",
        "description": "Il Piano Operativo di Sicurezza viene generato automaticamente dalla scheda cantiere, con rischi specifici, DPI, soggetti e misure gia compilati. Esce un DOCX professionale pronto per la firma.",
        "target_audience": ["sicurezza", "titolare"],
        "pain_points": ["scrivere il POS da zero ogni volta", "copiare dati gia inseriti altrove", "dimenticare un rischio specifico del cantiere", "POS generico che non dice nulla di utile"],
        "value_claim": "POS professionale generato in 2 minuti, non in 2 giorni",
        "proof_points": ["DOCX pronto per firma", "rischi specifici del cantiere", "soggetti gia compilati", "conforme al D.Lgs. 81/2008"],
        "demo_route": "/cantieri-sicurezza",
    },
    {
        "title": "Verifica Committenza AI",
        "type": "feature",
        "category": "compliance",
        "description": "L'AI analizza il profilo del committente e identifica automaticamente quali documenti servono, quali requisiti contrattuali verificare e quali rischi di conformita monitorare.",
        "target_audience": ["titolare", "ufficio_tecnico"],
        "pain_points": ["non sapere cosa chiedere al committente", "dimenticare documenti obbligatori per tipo di appalto", "scoprire requisiti mancanti dopo aver iniziato i lavori"],
        "value_claim": "Sapere esattamente cosa serve dal committente prima di iniziare",
        "proof_points": ["checklist committente automatica", "profili documentali per tipo appalto", "alert su documenti mancanti o scaduti"],
        "demo_route": "/commesse/com_demo_main",
    },
    {
        "title": "Pacchetti Documentali Intelligenti",
        "type": "feature",
        "category": "delivery",
        "description": "Il sistema assembla automaticamente il pacchetto documentale corretto per ogni commessa, verificando completezza e conformita. Poi lo invia via email con tracking completo.",
        "target_audience": ["ufficio_tecnico", "titolare"],
        "pain_points": ["assemblare documenti a mano per ogni consegna", "dimenticare un allegato nel pacchetto", "non sapere se il cliente ha ricevuto tutto", "inviare documenti sbagliati o non aggiornati"],
        "value_claim": "Pacchetto documentale completo, verificato e inviato in 3 click",
        "proof_points": ["verifica completezza automatica", "invio email con tracking", "storico invii per commessa"],
        "demo_route": "/pacchetti-documentali",
    },
    {
        "title": "Dashboard Cantiere Multilivello",
        "type": "feature",
        "category": "operations",
        "description": "Una dashboard che mostra lo stato di tutte le commesse, cantieri e obblighi su piu livelli. Semaforo verde/giallo/rosso per ogni area critica, KPI in tempo reale.",
        "target_audience": ["titolare", "ufficio_tecnico"],
        "pain_points": ["non avere una visione d'insieme di tutti i cantieri", "scoprire problemi quando e troppo tardi", "rincorrere informazioni tra fogli, email e telefonate"],
        "value_claim": "Tutti i cantieri sotto controllo in un solo colpo d'occhio",
        "proof_points": ["semaforo commesse", "KPI in tempo reale", "alert automatici", "visione multilivello"],
        "demo_route": "/dashboard",
    },
    {
        "title": "Profili Documentali per Committente",
        "type": "feature",
        "category": "compliance",
        "description": "Ogni committente ha un profilo documentale che definisce quali documenti richiede abitualmente. Quando crei una nuova commessa per quel committente, i requisiti sono gia pre-compilati.",
        "target_audience": ["ufficio_tecnico", "qualita"],
        "pain_points": ["rifare da zero la lista documenti per ogni commessa", "dimenticare che quel committente vuole documenti extra", "non ricordare le specifiche di un committente servito mesi fa"],
        "value_claim": "Il sistema ricorda cosa vuole ogni committente, tu no",
        "proof_points": ["profili riutilizzabili", "auto-compilazione requisiti", "storico per committente"],
        "demo_route": "/clients",
    },
    {
        "title": "Da Preventivo a Cantiere Pronto",
        "type": "demo_flow",
        "category": "workflow",
        "description": "Il flusso completo che parte dal preventivo e arriva al cantiere pronto con tutti gli obblighi sotto controllo. La dimostrazione piu forte del valore di NormaFacile.",
        "target_audience": ["titolare", "ufficio_tecnico", "sicurezza", "qualita"],
        "pain_points": ["processi frammentati tra 5 software diversi", "informazioni che si perdono tra un passaggio e l'altro", "nessuno sa a che punto siamo davvero", "rincorrere documenti all'ultimo momento"],
        "value_claim": "Un unico flusso dal preventivo alla consegna, senza perdere nulla per strada",
        "proof_points": ["preventivo -> istruttoria -> commessa -> obblighi -> POS -> documenti -> invio", "zero informazioni perse", "tracciabilita completa"],
        "demo_route": "/preventivi",
    },
]
