"""Content Engine — Seed data for 10 pre-loaded content sources.
Sorgenti reali basate sulle feature di NormaFacile 2.0.
Tono: B2B tecnico, italiano, concreto. Zero marketing generico.
"""

CONTENT_SOURCES_SEED = [
    {
        "code": "SRC_OBBLIGHI_COMMESSA",
        "title": "Registro Obblighi Commessa",
        "type": "feature",
        "category": "compliance_operativa",
        "target_audience": ["titolare", "ufficio_tecnico", "qualita", "sicurezza"],
        "pain_points": [
            "non so cosa manca davvero in una commessa",
            "i blocchi emergono troppo tardi",
            "le attivita sono sparse tra moduli diversi",
            "nessuno ha una lista unica delle cose da fare",
        ],
        "description": "Il Registro Obblighi raccoglie automaticamente da piu fonti tutto cio che manca, blocca o richiede attenzione su una commessa.",
        "value_claim": "Trasforma dati sparsi in azioni governabili con responsabili, scadenze e priorita.",
        "proof_points": [
            "sincronizza 8 fonti diverse",
            "deduplicazione automatica",
            "auto-close e riapertura automatica",
            "visibile in CommessaHub e Dashboard",
        ],
        "demo_route": "/commesse/demo/commessa-hub",
        "suggested_formats": ["linkedin_post", "reel_short", "carosello", "case_study"],
    },
    {
        "code": "SRC_ISTRUTTORIA_AI",
        "title": "Istruttoria AI da Preventivo",
        "type": "feature",
        "category": "ai_workflow",
        "target_audience": ["ufficio_tecnico", "preventivazione", "titolare"],
        "pain_points": [
            "dal preventivo alla commessa si perde tempo",
            "i dati vanno reinseriti piu volte",
            "la parte normativa viene capita troppo tardi",
            "il preventivo non diventa automaticamente istruttoria",
        ],
        "description": "NormaFacile legge il preventivo e propone una istruttoria tecnica e normativa strutturata.",
        "value_claim": "Riduce il data entry e anticipa le domande tecniche e normative gia in fase di avvio commessa.",
        "proof_points": [
            "analisi AI con review umana",
            "classificazione normativa",
            "domande residue ad alto impatto",
            "base per commessa pre-istruita",
        ],
        "demo_route": "/istruttoria/demo",
        "suggested_formats": ["linkedin_post", "reel_short", "carosello"],
    },
    {
        "code": "SRC_SEGMENTAZIONE_MISTA",
        "title": "Segmentazione Commessa Mista",
        "type": "feature",
        "category": "normativa",
        "target_audience": ["ufficio_tecnico", "qualita", "titolare"],
        "pain_points": [
            "una sola commessa contiene lavorazioni diverse",
            "si rischia di mischiare EN 1090, EN 13241 e generico",
            "una classificazione unica crea errori documentali",
        ],
        "description": "Il sistema segmenta le righe della commessa in rami normativi distinti e propone la struttura corretta.",
        "value_claim": "Evita errori di classificazione e separa correttamente i flussi normativi dentro la stessa commessa.",
        "proof_points": [
            "analisi riga per riga",
            "conferma utente",
            "creazione automatica rami normativi",
            "compatibile con emissioni progressive",
        ],
        "demo_route": "/istruttoria/demo/segmentazione",
        "suggested_formats": ["linkedin_post", "carosello", "case_study"],
    },
    {
        "code": "SRC_EVIDENCE_GATE",
        "title": "Evidence Gate per Emissioni",
        "type": "feature",
        "category": "qualita_documenti",
        "target_audience": ["qualita", "ufficio_tecnico", "titolare"],
        "pain_points": [
            "i documenti finali vengono emessi troppo presto",
            "mancano evidenze quando arriva il controllo",
            "non e chiaro cosa blocca davvero una DoP o una CE",
        ],
        "description": "L'Evidence Gate verifica emissione per emissione se esistono davvero tutte le evidenze necessarie prima di emettere i documenti finali.",
        "value_claim": "Blocca l'emissione quando mancano prove reali e rende chiaro cosa serve per sbloccare la commessa.",
        "proof_points": [
            "gate per emissione e non solo per commessa",
            "blockers e warnings strutturati",
            "supporto EN 1090 e EN 13241",
            "integrazione con Registro Obblighi",
        ],
        "demo_route": "/commesse/demo/emissioni",
        "suggested_formats": ["linkedin_post", "reel_short", "carosello", "case_study"],
    },
    {
        "code": "SRC_POS_DINAMICO",
        "title": "POS dinamico da Scheda Cantiere",
        "type": "feature",
        "category": "sicurezza",
        "target_audience": ["sicurezza", "ufficio_tecnico", "titolare"],
        "pain_points": [
            "il POS si rifa ogni volta quasi da zero",
            "si copiano vecchi file Word e si correggono a mano",
            "si dimenticano rischi, ruoli o allegati importanti",
        ],
        "description": "NormaFacile precompila la scheda cantiere, attiva rischi e DPI e genera una bozza POS DOCX modificabile partendo dalla commessa.",
        "value_claim": "Trasforma il POS da documento statico a bozza operativa guidata e contestualizzata.",
        "proof_points": [
            "motore AI sicurezza",
            "libreria rischi a 3 livelli",
            "gate POS",
            "generazione DOCX",
        ],
        "demo_route": "/sicurezza/demo/scheda-cantiere",
        "suggested_formats": ["linkedin_post", "reel_short", "case_study"],
    },
    {
        "code": "SRC_VERIFICA_COMMITTENZA",
        "title": "Verifica Committenza AI",
        "type": "feature",
        "category": "contratti_richieste",
        "target_audience": ["titolare", "ufficio_tecnico", "amministrazione", "qualita"],
        "pain_points": [
            "il cliente chiede cose extra dopo l'ordine",
            "capitolati e allegati vengono letti tardi",
            "si accettano richieste senza capirne l'impatto",
        ],
        "description": "Il sistema analizza contratto, capitolato e allegati del cliente per estrarre obblighi, anomalie e mismatch rispetto al preventivo.",
        "value_claim": "Fa emergere subito richieste strane, obblighi documentali e punti da chiarire prima che diventino problemi.",
        "proof_points": [
            "analisi AI con review umana",
            "mismatch con preventivo e commessa",
            "genera obblighi nel Registro",
            "collega richieste ai pacchetti documentali",
        ],
        "demo_route": "/committenza/demo",
        "suggested_formats": ["linkedin_post", "carosello", "case_study"],
    },
    {
        "code": "SRC_PACCHETTI_DOCUMENTALI",
        "title": "Pacchetti Documentali Intelligenti",
        "type": "feature",
        "category": "documentale",
        "target_audience": ["amministrazione", "sicurezza", "ufficio_tecnico", "titolare"],
        "pain_points": [
            "il cliente chiede sempre gli stessi documenti",
            "si perdono ore a cercare file e attestati",
            "si inviano documenti scaduti o incompleti",
        ],
        "description": "NormaFacile compone pacchetti documentali da inviare al cliente, verifica scadenze, segnala mancanze e invia via email con log.",
        "value_claim": "Riduce drasticamente il tempo per preparare e inviare dossier documentali corretti.",
        "proof_points": [
            "matching automatico documenti",
            "privacy level documenti",
            "preview invio email",
            "storico invii",
        ],
        "demo_route": "/pacchetti-documentali/demo",
        "suggested_formats": ["linkedin_post", "reel_short", "carosello"],
    },
    {
        "code": "SRC_DASHBOARD_MULTI",
        "title": "Dashboard Cantiere Multilivello",
        "type": "feature",
        "category": "controllo_manageriale",
        "target_audience": ["titolare", "responsabile_commessa", "ufficio_tecnico"],
        "pain_points": [
            "non ho una fotografia unica della commessa",
            "per capire i problemi devo aprire troppi moduli",
            "i blocchi emergono solo quando e troppo tardi",
        ],
        "description": "Una dashboard executive che mostra lo stato della commessa, dei rami normativi, della sicurezza, dei documenti e della committenza in un solo colpo d'occhio.",
        "value_claim": "Rende governabile una commessa complessa senza dover inseguire informazioni sparse.",
        "proof_points": [
            "KPI globali",
            "semaforo automatico",
            "drill-down 4 livelli",
            "integrazione con Registro Obblighi",
        ],
        "demo_route": "/cruscotto-cantiere",
        "suggested_formats": ["linkedin_post", "reel_short", "carosello"],
    },
    {
        "code": "SRC_PROFILI_COMMITTENTE",
        "title": "Profili Documentali per Committente",
        "type": "feature",
        "category": "riuso_operativo",
        "target_audience": ["amministrazione", "sicurezza", "titolare"],
        "pain_points": [
            "i clienti ricorrenti chiedono sempre le stesse cose",
            "ogni volta si ricostruisce il dossier da zero",
            "si rischia di dimenticare richieste tipiche del committente",
        ],
        "description": "Il sistema salva profili documentali riutilizzabili per i committenti ricorrenti e precompila i pacchetti in automatico.",
        "value_claim": "Trasforma l'esperienza accumulata su un cliente in velocita operativa sulle commesse successive.",
        "proof_points": [
            "creazione semi-automatica da pacchetto",
            "applica profilo a nuova commessa",
            "riduce attivita ripetitive",
            "coerenza tra commesse simili",
        ],
        "demo_route": "/pacchetti-documentali/profili",
        "suggested_formats": ["linkedin_post", "case_study", "carosello"],
    },
    {
        "code": "SRC_DEMO_END_TO_END",
        "title": "Da preventivo a cantiere pronto",
        "type": "demo_story",
        "category": "end_to_end",
        "target_audience": ["titolare", "partner", "investitore", "ufficio_tecnico"],
        "pain_points": [
            "i processi sono frammentati tra Word, Excel, email e cartelle",
            "la commessa prende forma troppo lentamente",
            "sicurezza, documenti e obblighi arrivano sempre tardi",
        ],
        "description": "Una demo completa che mostra il percorso dalla preventivazione alla commessa, alla sicurezza, agli obblighi e ai documenti da inviare.",
        "value_claim": "Mostra in pochi minuti il vero valore del sistema operativo di commessa.",
        "proof_points": [
            "preventivo",
            "istruttoria AI",
            "segmentazione",
            "commessa",
            "POS",
            "pacchetti documentali",
            "dashboard",
        ],
        "demo_route": "/demo/landing",
        "suggested_formats": ["reel_short", "case_study", "linkedin_post"],
    },
    {
        "code": "SRC_CASO_STUDIO_QUANTIFICATO",
        "title": "Caso Studio Quantificato — Da preventivo a cantiere pronto",
        "type": "case_study",
        "category": "commerciale",
        "target_audience": ["titolare", "partner", "investitore", "direttore_tecnico"],
        "pain_points": [
            "non ho numeri concreti per raccontare il valore del sistema",
            "i prospect chiedono risultati, non feature",
            "serve una storia credibile per vendere, non una brochure",
        ],
        "description": "Il caso studio pilota di Steel Project Design: dal preventivo al cantiere pronto, con metriche prudenziali su riduzione tempo POS (50-70%), preparazione dossier, visibilita commessa e riduzione rischio omissioni.",
        "value_claim": "Una storia concreta con numeri credibili, pronta per pitch, demo e contenuti derivati.",
        "proof_points": [
            "riduzione stimata 50-70% tempo preparazione POS",
            "tempo dossier cliente sensibilmente ridotto",
            "da controllo frammentato a vista unica commessa",
            "riduzione rischio omissioni documentali",
            "pagina pubblica dedicata: /caso-studio",
        ],
        "demo_route": "/caso-studio",
        "suggested_formats": ["linkedin_post", "carosello", "case_study", "reel_short"],
    },
]
